import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { MOCK_ALERTS } from '../constants';
import { AlertTriangle, Shield, CheckCircle } from 'lucide-react';

const Alerts = () => {
    const navigate = useNavigate();
    const [alerts] = useState(MOCK_ALERTS);

    const getSeverityColor = (sev: string) => {
        switch(sev) {
            case 'CRITICAL': return 'bg-red-500/10 text-red-500 border-red-500/20';
            case 'HIGH': return 'bg-orange-500/10 text-orange-500 border-orange-500/20';
            case 'MEDIUM': return 'bg-yellow-500/10 text-yellow-500 border-yellow-500/20';
            case 'LOW': return 'bg-blue-500/10 text-blue-500 border-blue-500/20';
            default: return 'bg-gray-500/10 text-gray-500 border-gray-500/20';
        }
    };

    return (
        <div className="flex flex-col gap-6">
            <div className="flex justify-between items-start">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white tracking-tight">Alert Feed</h1>
                    <p className="text-sm text-gray-600 dark:text-gray-400 mt-1">Real-time alerts generated by detection rules</p>
                </div>
            </div>

            <div className="bg-white dark:bg-gray-800 border border-gray-700 rounded-xl overflow-hidden">
                <table className="w-full text-left text-sm text-gray-600 dark:text-gray-400">
                    <thead className="text-xs uppercase bg-gray-50 dark:bg-gray-900/50 text-gray-500 border-b border-gray-700">
                        <tr>
                            <th className="px-6 py-4 font-semibold">ID & Time</th>
                            <th className="px-6 py-4 font-semibold">Severity</th>
                            <th className="px-6 py-4 font-semibold">Rule Triggered</th>
                            <th className="px-6 py-4 font-semibold">Host</th>
                            <th className="px-6 py-4 font-semibold">Status</th>
                            <th className="px-6 py-4 font-semibold text-right">Actions</th>
                        </tr>
                    </thead>
                    <tbody className="divide-y divide-gray-800">
                        {alerts.map(alert => (
                            <tr key={alert.id} className="hover:bg-white dark:bg-gray-800/80 transition-colors">
                                <td className="px-6 py-4">
                                    <div className="text-gray-900 dark:text-white font-medium">{alert.id}</div>
                                    <div className="text-xs mt-0.5">{alert.timestamp}</div>
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`px-2.5 py-1 text-[10px] font-bold uppercase tracking-wider rounded-md border ${getSeverityColor(alert.severity)}`}>
                                        {alert.severity}
                                    </span>
                                </td>
                                <td className="px-6 py-4">
                                    <div className="text-gray-800 dark:text-gray-300 font-medium">{alert.ruleTriggered}</div>
                                    <div className="text-xs text-gray-500 mt-1 font-mono">{alert.processName}</div>
                                </td>
                                <td className="px-6 py-4 font-mono text-gray-800 dark:text-gray-300">
                                    {alert.hostname}
                                </td>
                                <td className="px-6 py-4">
                                    <span className={`px-2 py-1 text-[10px] font-bold uppercase rounded ${alert.status === 'new' ? 'bg-blue-500/20 text-blue-400' : 'bg-gray-100 dark:bg-gray-700 text-gray-800 dark:text-gray-300'}`}>
                                        {alert.status}
                                    </span>
                                </td>
                                <td className="px-6 py-4 text-right">
                                    <button 
                                        onClick={() => navigate(`/alerts/${alert.id}`)}
                                        className="text-emerald-400 hover:text-emerald-300 font-medium text-sm transition-colors"
                                    >
                                        Investigate &rarr;
                                    </button>
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default Alerts;
